### ISSUE TITLE
Suggested Improvement

### ISSUE THREAD

**Issue by cdudhat** [learn-co-curriculum/yield-and-return-values#6]
While this learn along lab is trying to show return values originating from using yield blocks, essentially the example doesn't do anything of that sort. Despite creating a "collections" array, and trying to store return values from yield into the collections block, leaving the "hello" method's block same, does not yield any return value anyways. The final "collections" array is still an empty array with three "nil"s. Conceptually, it could have been better explained by changing the block to actually give a return value which would be collected in the "collections" array rather than "nil"
![screen shot 2016-09-12 at 9 52 46 pm](https://cloud.githubusercontent.com/assets/18668942/18458964/e0c7ea00-7933-11e6-8de0-4079ee256ade.png)

**Comment by sgharms** [comment]
Based on this comment, I believe you may have incorrectly understood the purpose of this code-along.

You want to take the array of names and use `hello` to return (as return value) a different array which is the "Hi, Tim", etc. so that the return value of `hello` is `["Hi, Tim", "Hi, Tom", "Hi, Jim"]`

I think you might not _quite_ be fully understanding the way this code is
working. Try discussing your issue via the [Ask a Question][AAQ] tool. You're
close, so stick with it!

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
