### ISSUE TITLE
Broken lab

### ISSUE THREAD

**Issue by curlywallst** [learn-co-curriculum/yield-and-return-values#8]
The Return From Yield Statements lab doesn't work.  It returns nil as written.  The whole collection array is unnecessary.  Here is what I did - I don't know if it's the best way but it works and is much simpler than the method in the lesson which doesn't actually work.

def hello(array)
  i = 0
  while i < array.length
    yield(array[i])
    i += 1
  end
  array
end

hello(["Tim", "Tom", "Jim"]) do |name|
  puts "Hi, #{name}"
  name
end

The key way explicitly returning name from the yield.  You can add it to a collection array if you want but you don't need to.  All the explanation is wrong too given that it presents as fact something that doesn't work.  I hope this helps!  Best, Nancy

**Comment by sgharms** [comment]
Based on this comment, I believe you may have incorrectly understood the purpose of this code-along.

You want to take the array of names and use `hello` to return (as return value) a different array which is the "Hi, Tim", etc. so that the return value of `hello` is `["Hi, Tim", "Hi, Tom", "Hi, Jim"]`

I think you might not _quite_ be fully understanding the way this code is
working. Try discussing your issue via the [Ask a Question][AAQ] tool. You're
close, so stick with it!

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
